[[object]]
id = "loc.crate3"
inherit = "loc.crate3"
contentGroup = "content.empty_crate"

[object.params]
"param.game_message" = "You search the crate but find nothing."

[[object]]
id = "loc.crate2_old"
inherit = "loc.crate2_old"
contentGroup = "content.empty_crate"

[object.params]
"param.game_message" = "You search the crate but find nothing."

[[object]]
id = "loc.crate3_old"
inherit = "loc.crate3_old"
contentGroup = "content.empty_crate"

[object.params]
"param.game_message" = "You search the crate but find nothing."

[[object]]
id = "loc.boxes"
inherit = "loc.boxes"
contentGroup = "content.empty_boxes"

[object.params]
"param.game_message" = "There is nothing interesting in these boxes."

[[object]]
id = "loc.sacks"
inherit = "loc.sacks"
contentGroup = "content.empty_sacks"

[object.params]
"param.game_message" = "There is nothing interesting in these sacks."

[[object]]
id = "loc.crate"
inherit = "loc.crate"
contentGroup = "content.empty_crate"

[object.params]
"param.game_message" = "You search the crate but find nothing."

[[object]]
id = "loc.bookcase"
inherit = "loc.bookcase"
contentGroup = "content.bookcase"

[[object]]
id = "loc.rustic_fencegate_l"
inherit = "loc.rustic_fencegate_l"
contentGroup = "content.closed_left_picketgate"

[object.params]
"param.next_loc_stage" = "loc.rustic_openfencegate_l"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.fencegate_l"
inherit = "loc.fencegate_l"
contentGroup = "content.closed_left_picketgate"

[object.params]
"param.next_loc_stage" = "loc.openfencegate_l"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.openfencegate_l"
inherit = "loc.openfencegate_l"
contentGroup = "content.opened_left_picketgate"

[object.params]
"param.closesound" = "synth.picketgate_close"
"param.next_loc_stage" = "loc.fencegate_l"

[[object]]
id = "loc.fencegate_r"
inherit = "loc.fencegate_r"
contentGroup = "content.closed_right_picketgate"

[object.params]
"param.next_loc_stage" = "loc.openfencegate_r"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.openfencegate_r"
inherit = "loc.openfencegate_r"
contentGroup = "content.opened_right_picketgate"

[object.params]
"param.closesound" = "synth.picketgate_close"
"param.next_loc_stage" = "loc.fencegate_r"

[[object]]
id = "loc.chicken_coop_empty"
inherit = "loc.chicken_coop_empty"
contentGroup = "content.chicken_coop"

[[object]]
id = "loc.chicken_coop_bare"
inherit = "loc.chicken_coop_bare"
contentGroup = "content.chicken_coop"

[[object]]
id = "loc.chicken_coop_bare2"
inherit = "loc.chicken_coop_bare2"
contentGroup = "content.chicken_coop"

[[object]]
id = "loc.fat_cow_fawest"
inherit = "loc.fat_cow_fawest"
contentGroup = "content.dairy_cow"

[[object]]
id = "loc.canoestation_log"
inherit = "loc.canoestation_log"

[object.params]
"param.levelrequire" = 12
"param.skill_xp" = 30
"param.next_loc_stage" = "loc.canoeing_log_sinking"

[[object]]
id = "loc.canoestation_dugout"
inherit = "loc.canoestation_dugout"

[object.params]
"param.levelrequire" = 27
"param.skill_xp" = 60
"param.next_loc_stage" = "loc.canoeing_dugout_sinking"

[[object]]
id = "loc.canoestation_stabledugout"
inherit = "loc.canoestation_stabledugout"

[object.params]
"param.levelrequire" = 42
"param.skill_xp" = 90
"param.next_loc_stage" = "loc.canoeing_catamaran_sinking"

[[object]]
id = "loc.canoestation_waka"
inherit = "loc.canoestation_waka"

[object.params]
"param.levelrequire" = 57
"param.skill_xp" = 150
"param.next_loc_stage" = "loc.canoeing_waka_sinking"

[[object]]
id = "loc.blankrunestone_exit_portal"
inherit = "loc.blankrunestone_exit_portal"

[[object]]
id = "loc.qip_cook_crate_stacked"
inherit = "loc.qip_cook_crate_stacked"
contentGroup = "content.empty_crate"

[object.params]
"param.game_message" = "You search the crate but find nothing."

[[object]]
id = "loc.qip_sheep_shearer_fencegate_l"
inherit = "loc.qip_sheep_shearer_fencegate_l"
contentGroup = "content.closed_left_picketgate"

[object.params]
"param.next_loc_stage" = "loc.qip_sheep_shearer_openfencegate_l"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.qip_sheep_shearer_fencegate_r"
inherit = "loc.qip_sheep_shearer_fencegate_r"
contentGroup = "content.closed_right_picketgate"

[object.params]
"param.next_loc_stage" = "loc.qip_sheep_shearer_openfencegate_r"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.qip_sheep_shearer_openfencegate_l"
inherit = "loc.qip_sheep_shearer_openfencegate_l"
contentGroup = "content.opened_left_picketgate"

[object.params]
"param.closesound" = "synth.door_close"
"param.next_loc_stage" = "loc.qip_sheep_shearer_fencegate_l"

[[object]]
id = "loc.qip_sheep_shearer_openfencegate_r"
inherit = "loc.qip_sheep_shearer_openfencegate_r"
contentGroup = "content.opened_right_picketgate"

[object.params]
"param.closesound" = "synth.door_close"
"param.next_loc_stage" = "loc.qip_sheep_shearer_fencegate_r"

[[object]]
id = "loc.rustic_fencegate_r"
inherit = "loc.rustic_fencegate_r"
contentGroup = "content.closed_right_picketgate"

[object.params]
"param.next_loc_stage" = "loc.rustic_openfencegate_r"
"param.opensound" = "synth.picketgate_open"

[[object]]
id = "loc.rustic_openfencegate_l"
inherit = "loc.rustic_openfencegate_l"
contentGroup = "content.opened_left_picketgate"

[object.params]
"param.closesound" = "synth.door_close"
"param.next_loc_stage" = "loc.rustic_fencegate_l"

[[object]]
id = "loc.rustic_openfencegate_r"
inherit = "loc.rustic_openfencegate_r"
contentGroup = "content.opened_right_picketgate"

[object.params]
"param.closesound" = "synth.door_close"
"param.next_loc_stage" = "loc.rustic_fencegate_r"

[[object]]
id = "loc.range"
inherit = "loc.range"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.lunar_pirate_cooking_range"
inherit = "loc.lunar_pirate_cooking_range"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.dorgesh_cooking_range1"
inherit = "loc.dorgesh_cooking_range1"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.dorgesh_cooking_range2"
inherit = "loc.dorgesh_cooking_range2"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.dorgesh_nursery_cooking_range"
inherit = "loc.dorgesh_nursery_cooking_range"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.ds2_guild_cooking_range"
inherit = "loc.ds2_guild_cooking_range"
contentGroup = "content.cooking_range_standard"

[[object]]
id = "loc.cooksquestrange"
inherit = "loc.cooksquestrange"
contentGroup = "content.cooking_range_lumbridge"

[[object]]
id = "loc.hos_cooking_range"
inherit = "loc.hos_cooking_range"
contentGroup = "content.cooking_range_hosidius"

[[object]]
id = "loc.hos_cooking_range_02"
inherit = "loc.hos_cooking_range_02"
contentGroup = "content.cooking_range_hosidius"

##Ladders
[[object]]
id = "loc.ladder"
inherit = "loc.ladder"
contentGroup = "content.ladder_up"

[[object]]
id = "loc.laddermiddle"
inherit = "loc.laddermiddle"
contentGroup = "content.ladder_option"

[[object]]
id = "loc.laddertop"
inherit = "loc.laddertop"
contentGroup = "content.ladder_down"

[object.params]
"param.climb_anim" = "seq.human_pickupfloor"

##Dungeon Ladders
[[object]]
id = "loc.qip_cook_trapdoor_open"
inherit = "loc.qip_cook_trapdoor_open"
contentGroup = "content.dungeonladder_down"

[object.params]
"param.climb_anim" = "seq.human_pickupfloor"

[[object]]
id = "loc.ladder_from_cellar"
inherit = "loc.ladder_from_cellar"
contentGroup = "content.dungeonladder_up"

##SpiralStaircases
[[object]]
id = "loc.spiralstairs"
inherit = "loc.spiralstairs"
contentGroup = "content.spiralstaircase_up"

[[object]]
id = "loc.spiralstairsmiddle"
inherit = "loc.spiralstairsmiddle"
contentGroup = "content.spiralstaircase_option"

[[object]]
id = "loc.spiralstairstop"
inherit = "loc.spiralstairstop"
contentGroup = "content.spiralstaircase_down"

[[object]]
id = "loc.spiralstairsbottom_3"
inherit = "loc.spiralstairsbottom_3"
contentGroup = "content.spiralstaircase_up"

[[object]]
id = "loc.spiralstairstop_3"
inherit = "loc.spiralstairstop_3"
contentGroup = "content.spiralstaircase_down"

[[object]]
id = "loc.sarim_spiralstairs"
inherit = "loc.sarim_spiralstairs"
contentGroup = "content.spiralstaircase_up"

[[object]]
id = "loc.sarim_spiralstairstop"
inherit = "loc.sarim_spiralstairstop"
contentGroup = "content.spiralstaircase_down"

[[object]]
id = "loc.fai_wiztower_spiralstairs"
inherit = "loc.fai_wiztower_spiralstairs"
contentGroup = "content.spiralstaircase_up"

[[object]]
id = "loc.fai_wiztower_spiralstairs_middle"
inherit = "loc.fai_wiztower_spiralstairs_middle"
contentGroup = "content.spiralstaircase_option"

[[object]]
id = "loc.fai_wiztower_spiralstairstop"
inherit = "loc.fai_wiztower_spiralstairstop"
contentGroup = "content.spiralstaircase_down"

##Bankbooths
[[object]]
id = "loc.aide_bankbooth"
inherit = "loc.aide_bankbooth"
contentGroup = "content.bank_booth"

[[object]]
id = "loc.aide_bankbooth_multi"
inherit = "loc.aide_bankbooth_multi"
contentGroup = "content.bank_booth"
