[[inventory]]
id = "inv.magictraining_inventory"
name = "Dusuri's Star Shop"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 800
delta = 0

size = 5

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.celestial_ring"
count = 50
restockCycles = 1

[[inventory.stock]]
obj = "obj.star_fragment"
count = 50
restockCycles = 1

[[inventory.stock]]
obj = "obj.star_reward_gem_bag"
count = 100
restockCycles = 1

[[inventory.stock]]
obj = "obj.star_pack_softclay"
count = 1000
restockCycles = 1

[[inventory.stock]]
obj = "obj.poh_tablet_shootingstar"
count = 100
restockCycles = 1
