[[mesanim]]
id="mesanim.quiz"
len1="seq.chatquiz1"
len2="seq.chatquiz2"
len3="seq.chatquiz3"
len4="seq.chatquiz4"

[[mesanim]]
id="mesanim.bored"
len1="seq.chatbored1"
len2="seq.chatbored2"
len3="seq.chatbored3"
len4="seq.chatbored4"

[[mesanim]]
id="mesanim.short"
len1="seq.chatneu_idle"
len2="seq.chatneu_idle"
len3="seq.chatneu_idle"
len4="seq.chatneu_idle"

[[mesanim]]
id="mesanim.happy"
len1="seq.chathap1"
len2="seq.chathap2"
len3="seq.chathap3"
len4="seq.chathap4"

[[mesanim]]
id="mesanim.shocked"
len1="seq.chathap1"
len2="seq.chathap2"
len3="seq.chathap3"
len4="seq.chathap4"

[[mesanim]]
id="mesanim.confused"
len1="seq.chatcon1"
len2="seq.chatcon2"
len3="seq.chatcon3"
len4="seq.chatcon4"

[[mesanim]]
id="mesanim.silent"
len1="seq.chat_pleased"
len2="seq.chat_pleased"
len3="seq.chat_pleased"
len4="seq.chat_pleased"

[[mesanim]]
id="mesanim.goblin"
len1="seq.chatgoblin1"
len2="seq.chatgoblin2"
len3="seq.chatgoblin3"
len4="seq.chatgoblin4"

[[mesanim]]
id="mesanim.neutral"
len1="seq.chatneu1"
len2="seq.chatneu2"
len3="seq.chatneu3"
len4="seq.chatneu4"

[[mesanim]]
id="mesanim.shifty"
len1="seq.chatshifty1"
len2="seq.chatshifty2"
len3="seq.chatshifty3"
len4="seq.chatshifty4"

[[mesanim]]
id="mesanim.worried"
len1="seq.chatscared1"
len2="seq.chatscared2"
len3="seq.chatscared3"
len4="seq.chatscared4"

[[mesanim]]
id="mesanim.drunk"
len1="seq.chatdrunk1"
len2="seq.chatdrunk2"
len3="seq.chatdrunk3"
len4="seq.chatdrunk4"

[[mesanim]]
id="mesanim.very_mad"
len1="seq.chat_furious"
len2="seq.chat_furious"
len3="seq.chat_furious"
len4="seq.chat_furious"

[[mesanim]]
id="mesanim.laugh"
len1="seq.chatlaugh1"
len2="seq.chatlaugh2"
len3="seq.chatlaugh3"
len4="seq.chatlaugh4"

[[mesanim]]
id="mesanim.mad_laugh"
len1="seq.chat_evillaugh"
len2="seq.chat_evillaugh"
len3="seq.chat_evillaugh"
len4="seq.chat_evillaugh"

[[mesanim]]
id="mesanim.sad"
len1="seq.chatsad1"
len2="seq.chatsad2"
len3="seq.chatsad3"
len4="seq.chatsad4"

[[mesanim]]
id="mesanim.angry"
len1="seq.chatang1"
len2="seq.chatang2"
len3="seq.chatang3"
len4="seq.chatang4"
